sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: "idG75T/K55981t8U4atWmKmxaBBLqPdiNXHtaX8N7mqjJ+4LI6ArnoeVTMXRnKsnBr89Ttx2ZqyGFf66sz637L/DDEXy44CPc+4Lwbn2f3FL1GzksWXUWLmMED5IltexbmLhlzSpbOVCcj1J3wAF4aQrruEOcMmqzCJ1YBTDU/WqGtl+w7q8JfQ0mSzYuImnE1tBq+hf/NdgKm30oHAg82VPPOrPak34f+k6oADadGse2cfUy8XxIrkOL4Q/+PNE2Tt+PGFK6o01zAUInEZqLtvRCFcvoRPXOqJKQ2DZdd5erCnGjETD43wG2kanMyR57bQoVFFYB3ml8Fof3wJY2CUKXfzRK813WxRnNA+Wl+fLLK446tn9vSdWmcNYBpdg4uodCuquuqAalY+AfMcfvIQGWwUn5ttC3EOlZJ8UtgpKwU8Dy9KbLej7Eyj1uyJ/3jnPBErAuGSW+ffx2tWVLYWfilmdYuDqnj+tQlCWT0i8YzHSmclOTVO1OLYi4lM6nTu9Rx5K4l5IaXMoRS1qkTMJbwJs2/4CqrvFeE4Y4ZBMkQjYP1qfJzP9jYs5drKAQ5bTe9IIrUDuXhlghEgo5+jjpM2DtDQJoFRXMQl9FqbUzgWmUNA7+NAFA0j6wWsiiuwkecDG9fy3S8V1uoHLLNw7f6REm0oj/TTukeIPVPQ="
  - secure: "AIgS2iB0PG+HRM3aIzjfJQKPNxfZWmy+zdTf5NW5YTssrV0JE9PKf5WRyZVTTFjq1Yn3L2+bLRr1E0cnjGy+tUzexPeTWy2Xxe222SxECCBnb7K5F8mwXjvj0fnynzs8V8qM3A2c7ldBKXQmpiAN+91Ks7GQW4YSr4CWA3viFHBalD9ChHyCmXxm044BF5f0nzcEm2wkw/zD33LOVPXFmhrViUAn1k4uu7oPcJ+98J2HDegpWI8+M4WH86JXrh9mZOZkiQ6x2+4uTj9Y+b54lQ4+tRbVWLRoSSFcAlnTNbQ85+seU2bSxPUkf6jhSoa381+Ls4cg8shotbMcZc9KGy7dZBec0+YeOBcSecpPU4m28m727Qi5717diCh3qF9qPK9/4kmcj0Gx/Wztaa8D1RuNOefhhFdI81JvewwLxjNEtIxX7IGBpmUOmtnYn3LywtVBhGlc82M6j5sSF4y7+mnOZMSJq+cut8nGRocU/piGMNB9tgz5wvc7UnFd4+eB6Wx3AremNPBGZaYf0Lt89a6NS/h02eWvfgczVA5etxVUA8QDojFfigHaEbPH7p1QXYR5cs5MUw8rq3Z5lSET2FOYlahqMxdTPhLygSOfzxF578rwkPMKBt/J4NPwa/1Nhj7Ktq+GlBqd4kMoBWx4+ckXz01dec1Fi42acCULITc="
  - secure: "Rmx6x/LtZCvvrvuPXWDpDBUYNBdCJj9Tr8JLdifPeCsjDvFvg9X0pdI1Z8d6flVo7TH/PzvIp71NuWbkyjSklSP10V+sK4zzsHOM3X7itoFwTlcfAXNbgFvz1+SVnQWzGcf8f68jT3pbgizFzCy+tnAXjqOgIegglhsvdR0AnUczzD8UD1ycXfOLG6Z+tFgG6TQwP59iXuPSqLP0u1YNNKScksO9qBBylHTGeyBRh1e3N4v6xiupxkAVtef9QSmTrELSmNwY2j1dIJOLQOWwy7XO6oYgnTJutTGeo8VLBTUi/WVTLyVG74ys9lefdKaK/Xodfj9U3qDm21rZ37sF6K75sccE4T7mP7xpuPeL12aGFoz6yI7oRwACDOVs8lv2QKZjImZx9jlHjP1Nd4Rk2Ou/paCEHhrvY9DEN3P+J54cOj4QctFpfpTXRG+5WjFsDZzq0RwYpJJiaBNtIc7Wy/RXoLJyK1hbV8j6bMDOCrguFLox7RIPFkrKAQHz2lKpw3usBi+gLOYmhl+w1XTcdFkoRfN5qoNHP22SSsdSaAsK3fcIanJX6J3c9MnZ6K5Vz45ytLeXZU78mTM4ZU5grVRPncE/cX9G3m95l1ojFJD7h5bKYYKkEh/djy/It9xq70m+1NCKTBhJGcX3eQdZyvNhJ7V15FUwQd3nGkHQSys="
  - secure: "u0b2u3hUNjBVnikNk/Ea7KmI3/1XQmgA7CaA2bGGmk6P6nDJvivg56668U9OAHZLG7C/tbYAiyh+C+Vt1MOotg8z0+RA+j04harPntBBwTFOiS6qCsB4eqFBIcGBqnHjh3STV0ifUPv3/7oGmdWa2iKWJvy9Hg1HTcbsXxYeZmCgtC3Rbo5sjwNSp8MG1XJv7NUS8IiMHEvQJN1LSafh+k0psYaNLeo6ScZF/+j2xbO6UKpSOxKEaXytXcK/qpWFE7ZAyGVukQYqyffcrsxUrfVv1J/aj7itkj1RDMVoDL9/+rpw4ZSYEYM9G760jLrjFyFiD9vx+kqxOfMPYiHJammJE04OqxgiEIWHq7sgK16Q36YpP3t702MKDFQnw5qXTqJ7XwzFZmqnWaGmRxy78SpU8W15vFZn+MoCn4aKz2OfzMcNGqO1QnrkQZM17HXQqhbxGWaYHVOutYIX3kIaBfcu+TtSglDS858xIDCyU55rb7avjD+Zr5R6SGC7dY7t71AR/XKzKGCsfRfGoopEA9CHTnHzlosnv1mhWnnQktlvVH0XWmaV6E9GtGkhb4H3hSAWV4Bu9OezMYPWdshsNLW0l7OVm0iqMjbEK/aVm9yHUXOZfy4VZVhGgeamaRboCPs2PdNv4h3ETCuUvS4AQbVCxj5RIQpzYV/9QRL9NhE="
  - COMMIT=${TRAVIS_COMMIT::7}
git:
  depth: 500
addons:
  sonarcloud:
    organization: anjeludo-github
    token:
      secure: "$SONAR_TOKEN"
script:
- "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=anjeludo/freelancer-kit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: "$HEROKU_API_KEY"
