sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: "DLUtOSBzONklmkiNOFAAp2m/V/JTBJrldnN5U//lsj02nCTNhdbyvr1zX2a2ecrmiksEODU4E6w8GGg/MRlJX4SND75amJrPAHMu76fsZVGGF42bO0Lj/bndYVsY59L93DC93a+BKB4PbGAfxBmg9NtqSXpP14M2Q+pm4CF3/QCte1pBjFhv/2u7gJ2sHUgeJuybXCXwGvkJBk7ftzD58DmkJDoXBIGkFXDWwmY6a7BLuJVHTNZjbscEVHpNirmWWTPSeCAV9srKfddtTYybfKx0O7wSPOMKSfR4Ed3r/8yuXvf2CLEiaE4p6TZ5Sce9iLkhPc4ivTO6k4wtG/eWdJptFfiD8hY7d8P1HZZ1he0BOvjyKmtBrcRllhlxqoqhtJcnjwM0qaChHkt1nITOAxtzFmI8z4pvtDo1bV25Y04G0OlKCUaMDuwh7TEufOKiQ/hOPJ5zz2LXlaIv2x0rxb5oSSmGTKc0io/mv8n+ZoUEdZxrKzKNOdpagKOitFE8902H8FXOYlT/qG/Jd2SNATwQZ40U+Eu+1UhcgojhgGMa3+9zgwimDu3yp9JEXQK+kSBakfqwsybe2ZT9QLwR/jxXGIjq8XnlkMzppgNm1RKX9aAmqSDgrIeLffcy95f9yfB1d9SGA0L7JBxEv0bp6ynWBjHiJBDv+LAwEuBpnyQ="
  - secure: "AIgS2iB0PG+HRM3aIzjfJQKPNxfZWmy+zdTf5NW5YTssrV0JE9PKf5WRyZVTTFjq1Yn3L2+bLRr1E0cnjGy+tUzexPeTWy2Xxe222SxECCBnb7K5F8mwXjvj0fnynzs8V8qM3A2c7ldBKXQmpiAN+91Ks7GQW4YSr4CWA3viFHBalD9ChHyCmXxm044BF5f0nzcEm2wkw/zD33LOVPXFmhrViUAn1k4uu7oPcJ+98J2HDegpWI8+M4WH86JXrh9mZOZkiQ6x2+4uTj9Y+b54lQ4+tRbVWLRoSSFcAlnTNbQ85+seU2bSxPUkf6jhSoa381+Ls4cg8shotbMcZc9KGy7dZBec0+YeOBcSecpPU4m28m727Qi5717diCh3qF9qPK9/4kmcj0Gx/Wztaa8D1RuNOefhhFdI81JvewwLxjNEtIxX7IGBpmUOmtnYn3LywtVBhGlc82M6j5sSF4y7+mnOZMSJq+cut8nGRocU/piGMNB9tgz5wvc7UnFd4+eB6Wx3AremNPBGZaYf0Lt89a6NS/h02eWvfgczVA5etxVUA8QDojFfigHaEbPH7p1QXYR5cs5MUw8rq3Z5lSET2FOYlahqMxdTPhLygSOfzxF578rwkPMKBt/J4NPwa/1Nhj7Ktq+GlBqd4kMoBWx4+ckXz01dec1Fi42acCULITc="
  - secure: "Rmx6x/LtZCvvrvuPXWDpDBUYNBdCJj9Tr8JLdifPeCsjDvFvg9X0pdI1Z8d6flVo7TH/PzvIp71NuWbkyjSklSP10V+sK4zzsHOM3X7itoFwTlcfAXNbgFvz1+SVnQWzGcf8f68jT3pbgizFzCy+tnAXjqOgIegglhsvdR0AnUczzD8UD1ycXfOLG6Z+tFgG6TQwP59iXuPSqLP0u1YNNKScksO9qBBylHTGeyBRh1e3N4v6xiupxkAVtef9QSmTrELSmNwY2j1dIJOLQOWwy7XO6oYgnTJutTGeo8VLBTUi/WVTLyVG74ys9lefdKaK/Xodfj9U3qDm21rZ37sF6K75sccE4T7mP7xpuPeL12aGFoz6yI7oRwACDOVs8lv2QKZjImZx9jlHjP1Nd4Rk2Ou/paCEHhrvY9DEN3P+J54cOj4QctFpfpTXRG+5WjFsDZzq0RwYpJJiaBNtIc7Wy/RXoLJyK1hbV8j6bMDOCrguFLox7RIPFkrKAQHz2lKpw3usBi+gLOYmhl+w1XTcdFkoRfN5qoNHP22SSsdSaAsK3fcIanJX6J3c9MnZ6K5Vz45ytLeXZU78mTM4ZU5grVRPncE/cX9G3m95l1ojFJD7h5bKYYKkEh/djy/It9xq70m+1NCKTBhJGcX3eQdZyvNhJ7V15FUwQd3nGkHQSys="
  - secure: "u0b2u3hUNjBVnikNk/Ea7KmI3/1XQmgA7CaA2bGGmk6P6nDJvivg56668U9OAHZLG7C/tbYAiyh+C+Vt1MOotg8z0+RA+j04harPntBBwTFOiS6qCsB4eqFBIcGBqnHjh3STV0ifUPv3/7oGmdWa2iKWJvy9Hg1HTcbsXxYeZmCgtC3Rbo5sjwNSp8MG1XJv7NUS8IiMHEvQJN1LSafh+k0psYaNLeo6ScZF/+j2xbO6UKpSOxKEaXytXcK/qpWFE7ZAyGVukQYqyffcrsxUrfVv1J/aj7itkj1RDMVoDL9/+rpw4ZSYEYM9G760jLrjFyFiD9vx+kqxOfMPYiHJammJE04OqxgiEIWHq7sgK16Q36YpP3t702MKDFQnw5qXTqJ7XwzFZmqnWaGmRxy78SpU8W15vFZn+MoCn4aKz2OfzMcNGqO1QnrkQZM17HXQqhbxGWaYHVOutYIX3kIaBfcu+TtSglDS858xIDCyU55rb7avjD+Zr5R6SGC7dY7t71AR/XKzKGCsfRfGoopEA9CHTnHzlosnv1mhWnnQktlvVH0XWmaV6E9GtGkhb4H3hSAWV4Bu9OezMYPWdshsNLW0l7OVm0iqMjbEK/aVm9yHUXOZfy4VZVhGgeamaRboCPs2PdNv4h3ETCuUvS4AQbVCxj5RIQpzYV/9QRL9NhE="
  - COMMIT=${TRAVIS_COMMIT::7}

git:
  depth: 500

addons:
  sonarcloud:
    organization: "anjeludo-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=anjeludo/freelancer-kit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY

